version: "3.8"

services:
  nginx:
    image: "nginx:stable"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./frontend:/usr/share/nginx/html
    ports:
      - 8080:80

  chatting:
    build: ./chatting
    env_file:
      - ./env/chatting.env

  game:
    build: ./game
    env_file:
      - ./env/game.env

  user-management:
    build: ./user-management
    env_file:
      - ./env/user-management.env
